name: foodcourt_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # state management
  provider: ^6.1.1
  # .env files
  flutter_dotenv: ^5.0.2
  # animation
  animate_do: ^3.3.3
  # location package
  geolocator: ^11.0.0
  # logger for viewing error efficiently
  logger: ^2.0.2+1
  # getting request
  http: ^1.2.0
  # for testing 
  mockito: ^5.4.4
  #shared prefference storage for persisting 
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/cities/
    - keys.env

